const data = {
  products: [
    {
      name: 'Free Shirt',
      category: 'Shirt',
      image: '/images/image1.jpg',
      price: 105,
      brand: 'Nike',
      rating: 4.1,
      countInStock: 20,
      description: 'A Popular Free Shirt',
    },
    {
      name: 'Slim Shirt',
      category: 'Shirt',
      image: '/images/image2.jpg',
      price: 120,
      brand: 'Lacoste',
      rating: 4.3,
      countInStock: 29,
      description: 'A Popular Slim Shirt',
    },
    {
      name: 'Fit Shirt',
      category: 'Shirt',
      image: '/images/image3.jpg',
      price: 110,
      brand: 'Polo',
      rating: 4.5,
      countInStock: 21,
      description: 'A Popular Fit Shirt',
    },
    {
      name: 'Fit Pant',
      category: 'Pant',
      image: '/images/image4.jpg',
      price: 100,
      brand: 'Zara',
      rating: 4.7,
      countInStock: 25,
      description: 'A Classic Fit Pant',
    },
    {
      name: 'Smart Pant',
      category: 'Pant',
      image: '/images/image5.jpg',
      price: 90,
      brand: 'Casley',
      rating: 4.5,
      countInStock: 30,
      description: 'A Popular Smart Pant',
    },
    {
      name: 'Free Pant',
      category: 'Pant',
      image: '/images/image6.jpg',
      price: 80,
      brand: 'Nike',
      rating: 4.0,
      countInStock: 20,
      description: 'A Popular Free Pant',
    },
  ],
};

export default data;